from enum import Enum

class MappingStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    PROPOSED = "PROPOSED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"

class MappingMethod(str, Enum):
    DIRECT_SKILL_MATCH = "DIRECT_SKILL_MATCH"
    ALIAS_MATCH = "ALIAS_MATCH"
    RULE_BASED = "RULE_BASED"
    SEMANTIC_MATCH = "SEMANTIC_MATCH"
    GITHUB_OBSERVATION = "GITHUB_OBSERVATION"
    DOCUMENT_EXTRACTION = "DOCUMENT_EXTRACTION"
    HUMAN_VERIFIED = "HUMAN_VERIFIED"
    SYSTEM_DERIVED = "SYSTEM_DERIVED"

class EvidenceStrength(str, Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"
