"""initial_domain_schema

Revision ID: c1b2e19bb043
Revises: 
Create Date: 2026-09-03 20:09:32.761483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b2e19bb043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('size_range', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('difficulty_level', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('aishe_code', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('accreditation', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('title')
    )
    op.create_table('competency_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_assessments_competency_id'), 'competency_assessments', ['competency_id'], unique=False)
    op.create_table('competency_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_competency_id', sa.String(length=36), nullable=False),
    sa.Column('target_competency_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_competency_id', 'target_competency_id', 'relationship_type', name='uq_competency_relationship')
    )
    op.create_index(op.f('ix_competency_relationships_source_competency_id'), 'competency_relationships', ['source_competency_id'], unique=False)
    op.create_index(op.f('ix_competency_relationships_target_competency_id'), 'competency_relationships', ['target_competency_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('hod_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_department_institution_code')
    )
    op.create_index(op.f('ix_departments_institution_id'), 'departments', ['institution_id'], unique=False)
    op.create_table('learning_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_competency_id'), 'learning_resources', ['competency_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('stipend_or_salary', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_competencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_skills_competency_id'), 'skills', ['competency_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('faculty',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_faculty_department_id'), 'faculty', ['department_id'], unique=False)
    op.create_index(op.f('ix_faculty_institution_id'), 'faculty', ['institution_id'], unique=False)
    op.create_table('industry_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_industry_users_company_id'), 'industry_users', ['company_id'], unique=False)
    op.create_table('opportunity_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('role_title', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_blueprints_company_id'), 'opportunity_blueprints', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunity_blueprints_opportunity_id'), 'opportunity_blueprints', ['opportunity_id'], unique=False)
    op.create_table('skill_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('alias_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias_name'), 'skill_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_skill_aliases_skill_id'), 'skill_aliases', ['skill_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_number', sa.String(length=100), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_enrollment_number'), 'students', ['enrollment_number'], unique=True)
    op.create_index(op.f('ix_students_institution_id'), 'students', ['institution_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_breakdown', sa.JSON(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'student_id', name='uq_opportunity_student_application')
    )
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('integrity_score', sa.Float(), nullable=True),
    sa.Column('integrity_hash', sa.String(length=128), nullable=True),
    sa.Column('post_mortem_data', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['competency_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_student_id'), 'assessment_results', ['student_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuing_organization', sa.String(length=200), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=100), nullable=True),
    sa.Column('credential_url', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_student_id'), 'certifications', ['student_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_entity_id'), 'evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_student_id'), 'evidence', ['student_id'], unique=False)
    op.create_table('internships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_student_id'), 'internships', ['student_id'], unique=False)
    op.create_table('opportunity_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blueprint_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('importance', sa.String(length=30), nullable=True),
    sa.Column('min_proficiency', sa.String(length=30), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['opportunity_blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_competencies_blueprint_id'), 'opportunity_competencies', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_opportunity_competencies_competency_id'), 'opportunity_competencies', ['competency_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('demonstrated_skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_student_id'), 'projects', ['student_id'], unique=False)
    op.create_table('student_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'competency_id', name='uq_student_competency')
    )
    op.create_index(op.f('ix_student_competencies_competency_id'), 'student_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_student_competencies_student_id'), 'student_competencies', ['student_id'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_table('evidence_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('verifier_id', sa.String(length=36), nullable=True),
    sa.Column('verifier_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attestation_digest', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_verifications_evidence_id'), 'evidence_verifications', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_verifications_verifier_id'), 'evidence_verifications', ['verifier_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('package_offered', sa.String(length=100), nullable=True),
    sa.Column('offer_letter_url', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placements')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_evidence_verifications_verifier_id'), table_name='evidence_verifications')
    op.drop_index(op.f('ix_evidence_verifications_evidence_id'), table_name='evidence_verifications')
    op.drop_table('evidence_verifications')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_student_competencies_student_id'), table_name='student_competencies')
    op.drop_index(op.f('ix_student_competencies_competency_id'), table_name='student_competencies')
    op.drop_table('student_competencies')
    op.drop_index(op.f('ix_projects_student_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_opportunity_competencies_competency_id'), table_name='opportunity_competencies')
    op.drop_index(op.f('ix_opportunity_competencies_blueprint_id'), table_name='opportunity_competencies')
    op.drop_table('opportunity_competencies')
    op.drop_index(op.f('ix_internships_student_id'), table_name='internships')
    op.drop_table('internships')
    op.drop_index(op.f('ix_evidence_student_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_entity_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_certifications_student_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_assessment_results_student_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_students_institution_id'), table_name='students')
    op.drop_index(op.f('ix_students_enrollment_number'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_skill_aliases_skill_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias_name'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_opportunity_blueprints_opportunity_id'), table_name='opportunity_blueprints')
    op.drop_index(op.f('ix_opportunity_blueprints_company_id'), table_name='opportunity_blueprints')
    op.drop_table('opportunity_blueprints')
    op.drop_index(op.f('ix_industry_users_company_id'), table_name='industry_users')
    op.drop_table('industry_users')
    op.drop_index(op.f('ix_faculty_institution_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_department_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_competency_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_learning_resources_competency_id'), table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_departments_institution_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_competency_relationships_target_competency_id'), table_name='competency_relationships')
    op.drop_index(op.f('ix_competency_relationships_source_competency_id'), table_name='competency_relationships')
    op.drop_table('competency_relationships')
    op.drop_index(op.f('ix_competency_assessments_competency_id'), table_name='competency_assessments')
    op.drop_table('competency_assessments')
    op.drop_table('roles_catalog')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_table('competencies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
