"""competency_foundation_taxonomy

Revision ID: e8ad73b71690
Revises: c1b2e19bb043
Create Date: 2026-09-03 21:12:00.328201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ad73b71690'
down_revision: Union[str, Sequence[str], None] = 'c1b2e19bb043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_code'), 'domains', ['code'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_domain_id'), 'categories', ['domain_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('role_competency_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('required_proficiency', sa.String(length=30), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'competency_id', name='uq_role_competency_requirement')
    )
    op.create_index(op.f('ix_role_competency_requirements_competency_id'), 'role_competency_requirements', ['competency_id'], unique=False)
    op.create_index(op.f('ix_role_competency_requirements_role_id'), 'role_competency_requirements', ['role_id'], unique=False)
    op.create_table('skill_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_weight', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'competency_id', name='uq_skill_competency')
    )
    op.create_index(op.f('ix_skill_competencies_competency_id'), 'skill_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_skill_competencies_skill_id'), 'skill_competencies', ['skill_id'], unique=False)
    op.add_column('competencies', sa.Column('domain_id', sa.String(length=36), nullable=True))
    op.add_column('competencies', sa.Column('category_id', sa.String(length=36), nullable=True))
    op.add_column('competencies', sa.Column('slug', sa.String(length=150), nullable=True))
    op.add_column('competencies', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.add_column('competencies', sa.Column('source_type', sa.String(length=50), server_default='SYSTEM', nullable=False))
    op.add_column('competencies', sa.Column('source_reference', sa.String(length=255), nullable=True))
    op.add_column('competencies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE competencies SET slug = lower(replace(code, '_', '-')) WHERE slug IS NULL;")
    op.alter_column('competencies', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_competencies_category_id'), 'competencies', ['category_id'], unique=False)
    op.create_index(op.f('ix_competencies_domain_id'), 'competencies', ['domain_id'], unique=False)
    op.create_index(op.f('ix_competencies_slug'), 'competencies', ['slug'], unique=True)
    op.create_foreign_key(None, 'competencies', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'competencies', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('competency_relationships', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.add_column('competency_relationships', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint('chk_no_self_competency_relationship', 'competency_relationships', 'source_competency_id != target_competency_id')
    op.add_column('roles_catalog', sa.Column('domain_id', sa.String(length=36), nullable=True))
    op.add_column('roles_catalog', sa.Column('slug', sa.String(length=150), nullable=True))
    op.add_column('roles_catalog', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.add_column('roles_catalog', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE roles_catalog SET slug = lower(replace(code, '_', '-')) WHERE slug IS NULL;")
    op.create_index(op.f('ix_roles_catalog_domain_id'), 'roles_catalog', ['domain_id'], unique=False)
    op.create_index(op.f('ix_roles_catalog_slug'), 'roles_catalog', ['slug'], unique=True)
    op.create_foreign_key(None, 'roles_catalog', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.add_column('skills', sa.Column('domain_id', sa.String(length=36), nullable=True))
    op.add_column('skills', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.add_column('skills', sa.Column('source_type', sa.String(length=50), server_default='SYSTEM', nullable=False))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('skills', 'competency_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('skills_slug_key'), 'skills', type_='unique')
    op.create_index(op.f('ix_skills_domain_id'), 'skills', ['domain_id'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.drop_constraint(op.f('skills_competency_id_fkey'), 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'skills', 'competencies', ['competency_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(op.f('skills_competency_id_fkey'), 'skills', 'competencies', ['competency_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_domain_id'), table_name='skills')
    op.create_unique_constraint(op.f('skills_slug_key'), 'skills', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('skills', 'competency_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'source_type')
    op.drop_column('skills', 'status')
    op.drop_column('skills', 'domain_id')
    op.drop_constraint(None, 'roles_catalog', type_='foreignkey')
    op.drop_index(op.f('ix_roles_catalog_slug'), table_name='roles_catalog')
    op.drop_index(op.f('ix_roles_catalog_domain_id'), table_name='roles_catalog')
    op.drop_column('roles_catalog', 'updated_at')
    op.drop_column('roles_catalog', 'status')
    op.drop_column('roles_catalog', 'slug')
    op.drop_column('roles_catalog', 'domain_id')
    op.drop_constraint('chk_no_self_competency_relationship', 'competency_relationships', type_='check')
    op.drop_column('competency_relationships', 'created_at')
    op.drop_column('competency_relationships', 'status')
    op.drop_constraint(None, 'competencies', type_='foreignkey')
    op.drop_constraint(None, 'competencies', type_='foreignkey')
    op.drop_index(op.f('ix_competencies_slug'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_domain_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_category_id'), table_name='competencies')
    op.alter_column('competencies', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('competencies', 'updated_at')
    op.drop_column('competencies', 'source_reference')
    op.drop_column('competencies', 'source_type')
    op.drop_column('competencies', 'status')
    op.drop_column('competencies', 'slug')
    op.drop_column('competencies', 'category_id')
    op.drop_column('competencies', 'domain_id')
    op.drop_index(op.f('ix_skill_competencies_skill_id'), table_name='skill_competencies')
    op.drop_index(op.f('ix_skill_competencies_competency_id'), table_name='skill_competencies')
    op.drop_table('skill_competencies')
    op.drop_index(op.f('ix_role_competency_requirements_role_id'), table_name='role_competency_requirements')
    op.drop_index(op.f('ix_role_competency_requirements_competency_id'), table_name='role_competency_requirements')
    op.drop_table('role_competency_requirements')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_domain_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_domains_code'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
