"""skill_aliases_normalization

Revision ID: e904c4bed880
Revises: e8ad73b71690
Create Date: 2026-09-03 21:32:23.525427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e904c4bed880'
down_revision: Union[str, Sequence[str], None] = 'e8ad73b71690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_aliases', sa.Column('normalized_alias', sa.String(length=150), nullable=False))
    op.add_column('skill_aliases', sa.Column('source_type', sa.String(length=50), server_default='SYSTEM', nullable=False))
    op.add_column('skill_aliases', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.add_column('skill_aliases', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skill_aliases', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_skill_aliases_normalized_alias'), 'skill_aliases', ['normalized_alias'], unique=False)
    op.create_unique_constraint('uq_skill_alias_normalized', 'skill_aliases', ['normalized_alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skill_alias_normalized', 'skill_aliases', type_='unique')
    op.drop_index(op.f('ix_skill_aliases_normalized_alias'), table_name='skill_aliases')
    op.drop_column('skill_aliases', 'updated_at')
    op.drop_column('skill_aliases', 'created_at')
    op.drop_column('skill_aliases', 'status')
    op.drop_column('skill_aliases', 'source_type')
    op.drop_column('skill_aliases', 'normalized_alias')
    # ### end Alembic commands ###
